<script src="{{ URL::asset('build/libs/@ckeditor/ckeditor5-build-classic/build/ckeditor.js') }}"></script>

<script>
    // Initialize CKEditor for English content
    let enEditorInstance = null;
    let bnEditorInstance = null;

    // Override ClassicEditor.create to prevent duplicate initialization
    (function() {
        if (typeof ClassicEditor !== 'undefined') {
            const originalCreate = ClassicEditor.create.bind(ClassicEditor);
            
            ClassicEditor.create = function(element) {
                // If this is our English editor and already initialized, return existing instance
                if (element && element.id === 'ckeditor-en' && enEditorInstance) {
                    return Promise.resolve(enEditorInstance);
                }
                
                // If this is our Bengali editor and already initialized, return existing instance
                if (element && element.id === 'ckeditor-bn' && bnEditorInstance) {
                    return Promise.resolve(bnEditorInstance);
                }
                
                // Otherwise, create normally
                return originalCreate(element).then(function(editor) {
                    if (element && element.id === 'ckeditor-en') {
                        enEditorInstance = editor;
                        editor.ui.view.editable.element.style.height = '300px';
                        
                        // Ensure content syncs on form submit
                        const form = document.getElementById('create-custom-page-form') || document.getElementById('edit-custom-page-form');
                        if (form) {
                            form.addEventListener('submit', function() {
                                editor.updateSourceElement();
                            });
                        }
                    }
                    
                    if (element && element.id === 'ckeditor-bn') {
                        bnEditorInstance = editor;
                        editor.ui.view.editable.element.style.height = '300px';
                        
                        // Ensure content syncs on form submit
                        const form = document.getElementById('create-custom-page-form') || document.getElementById('edit-custom-page-form');
                        if (form) {
                            form.addEventListener('submit', function() {
                                editor.updateSourceElement();
                            });
                        }
                    }
                    
                    return editor;
                });
            };
        }
    })();

    // Initialize editors
    document.addEventListener('DOMContentLoaded', function() {
        if (typeof ClassicEditor !== 'undefined') {
            // Initialize English editor
            const enTextarea = document.querySelector('#ckeditor-en');
            if (enTextarea) {
                ClassicEditor
                    .create(enTextarea)
                    .then(function(editor) {
                        enEditorInstance = editor;
                        editor.ui.view.editable.element.style.height = '300px';
                    })
                    .catch(function(error) {
                        console.error('Error initializing English editor:', error);
                    });
            }

            // Initialize Bengali editor
            const bnTextarea = document.querySelector('#ckeditor-bn');
            if (bnTextarea) {
                ClassicEditor
                    .create(bnTextarea)
                    .then(function(editor) {
                        bnEditorInstance = editor;
                        editor.ui.view.editable.element.style.height = '300px';
                    })
                    .catch(function(error) {
                        console.error('Error initializing Bengali editor:', error);
                    });
            }
        }
    });

    // Auto-generate slug from name
    document.addEventListener('DOMContentLoaded', function() {
        const nameInput = document.getElementById('name');
        const slugInput = document.getElementById('slug');
        
        if (nameInput && slugInput) {
            nameInput.addEventListener('input', function() {
                // Only auto-generate if slug is empty or matches the old name
                if (!slugInput.value || slugInput.dataset.autoGenerated === 'true') {
                    const slug = this.value
                        .toLowerCase()
                        .trim()
                        .replace(/[^\w\s-]/g, '')
                        .replace(/[\s_-]+/g, '-')
                        .replace(/^-+|-+$/g, '');
                    slugInput.value = slug;
                    slugInput.dataset.autoGenerated = 'true';
                }
            });

            // Mark slug as manually edited if user types in it
            slugInput.addEventListener('input', function() {
                if (this.value) {
                    this.dataset.autoGenerated = 'false';
                }
            });
        }

        const copyButton = document.getElementById('copy-custom-page-url');
        const publicUrlInput = document.getElementById('custom-page-public-url');

        if (copyButton && publicUrlInput) {
            copyButton.addEventListener('click', async function() {
                try {
                    await navigator.clipboard.writeText(publicUrlInput.value);
                    copyButton.textContent = 'Copied';
                    window.setTimeout(function() {
                        copyButton.textContent = 'Copy';
                    }, 1500);
                } catch (error) {
                    publicUrlInput.select();
                }
            });
        }
    });
</script>
